### ISSUE TITLE
Migration

### ISSUE THREAD

**Issue by mousavian** [ayooby/whatisit#2]
I saw you have commited your DB scheme as phpmyadmin export file. [HERE](https://github.com/sajad666/whatisit/blob/master/sql-import/whatisit.sql)

Laravel has its own solution for that called Migration and Seeding.

Go search for "migration in laravel", then update the project accordingly.

Email me in case you had any difficulty.

**Comment by ayooby** [comment]
Yes and i knew it but i dont' have much time for making any migrate file and sorry about that

**Comment by mousavian** [comment]
@sajad666 No problem dude. Just put this issue open till you fix it. ;)
