### ISSUE TITLE
Typo in model name

### ISSUE THREAD

**Issue by mousavian** [ayooby/whatisit#4]
In this line [AnswerController.php#L49](https://github.com/sajad666/whatisit/blob/master/app/controllers/AnswerController.php#L49)

You have a typo ( mistake in writing ).
You should write exactly the same name of the model as you used [here](https://github.com/sajad666/whatisit/blob/master/app/models/Answer.php)

It may works for you now since you are using Windows OS but as soon as you go in production environment in Linux, you'll have an ERROR :-1: 

So kindly fix this now.

**Comment by ayooby** [comment]
not happening again :+1:
